import { Review } from "./types";

export const mockReviews: Review[] = [
  {
    id: "1",
    platform_source: "heureka",
    external_review_id: "heu-001",
    country_code: "CZ",
    rating: 5,
    review_text: "Skvělá kvalita vlny, rychlé doručení. Určitě objednám znovu!",
    review_text_cz: "Skvělá kvalita vlny, rychlé doručení. Určitě objednám znovu!",
    customer_name_extracted: "Jana Novotná",
    order_id: "ord-101",
    match_confidence: "exact",
    ai_category: "product",
    ai_sentiment: "positive",
    response_draft: "Děkujeme za Vaši recenzi, Jano! Těšíme se na Vaši další objednávku.",
    status: "pending",
    created_at: "2026-05-12T10:30:00Z",
    replied_at: null,
    order: {
      id: "ord-101",
      external_order_id: "WV-CZ-20260510-001",
      customer_email: "jana.novotna@email.cz",
      customer_name: "Jana Novotná",
      shipping_country: "CZ",
      created_at: "2026-05-10T08:00:00Z",
    },
  },
  {
    id: "2",
    platform_source: "trusted_shops",
    external_review_id: "ts-002",
    country_code: "DE",
    rating: 2,
    review_text: "Die Lieferung hat über 2 Wochen gedauert. Die Wolle selbst ist okay, aber der Versand war enttäuschend.",
    review_text_cz: "Doručení trvalo přes 2 týdny. Vlna samotná je ok, ale doprava byla zklamáním.",
    customer_name_extracted: "Markus Weber",
    order_id: null,
    match_confidence: "unverified",
    ai_category: "logistics",
    ai_sentiment: "negative",
    response_draft: null,
    status: "pending",
    created_at: "2026-05-11T14:20:00Z",
    replied_at: null,
  },
  {
    id: "3",
    platform_source: "trustpilot",
    external_review_id: "tp-003",
    country_code: "DE",
    rating: 4,
    review_text: "Gute Auswahl an Garnen. Die Website könnte etwas übersichtlicher sein.",
    review_text_cz: "Dobrý výběr přízí. Webové stránky by mohly být přehlednější.",
    customer_name_extracted: "Anna Müller",
    order_id: "ord-102",
    match_confidence: "fuzzy",
    ai_category: "web",
    ai_sentiment: "positive",
    response_draft: "Vielen Dank für Ihr Feedback, Anna! Wir arbeiten kontinuierlich an der Verbesserung unserer Website.",
    status: "pending",
    created_at: "2026-05-10T09:15:00Z",
    replied_at: null,
    order: {
      id: "ord-102",
      external_order_id: "WV-DE-20260508-012",
      customer_email: "anna.mueller@gmail.com",
      customer_name: "Anna Mueller",
      shipping_country: "DE",
      created_at: "2026-05-08T12:00:00Z",
    },
  },
  {
    id: "4",
    platform_source: "trusted_shops",
    external_review_id: "ts-004",
    country_code: "CH",
    rating: 5,
    review_text: "Wunderschöne Wolle, tolle Farben! Schnelle Lieferung in die Schweiz.",
    review_text_cz: "Nádherná vlna, skvělé barvy! Rychlé doručení do Švýcarska.",
    customer_name_extracted: "Sophie Brunner",
    order_id: "ord-103",
    match_confidence: "exact",
    ai_category: "product",
    ai_sentiment: "positive",
    response_draft: "Vielen Dank, Sophie! Es freut uns, dass Ihnen unsere Wolle gefällt.",
    status: "replied",
    created_at: "2026-05-09T16:45:00Z",
    replied_at: "2026-05-10T08:00:00Z",
    order: {
      id: "ord-103",
      external_order_id: "WV-CH-20260507-005",
      customer_email: "sophie.b@bluewin.ch",
      customer_name: "Sophie Brunner",
      shipping_country: "CH",
      created_at: "2026-05-07T10:30:00Z",
    },
  },
  {
    id: "5",
    platform_source: "heureka",
    external_review_id: "heu-005",
    country_code: "SK",
    rating: 3,
    review_text: "Vlna je pekná, ale chýbali mi pletacie ihlice, ktoré som si objednal.",
    review_text_cz: "Vlna je hezká, ale chyběly mi pletací jehlice, které jsem si objednal.",
    customer_name_extracted: "Peter Kováč",
    order_id: "ord-104",
    match_confidence: "exact",
    ai_category: "service",
    ai_sentiment: "neutral",
    response_draft: null,
    status: "pending",
    created_at: "2026-05-13T11:00:00Z",
    replied_at: null,
    order: {
      id: "ord-104",
      external_order_id: "WV-SK-20260511-003",
      customer_email: "peter.kovac@azet.sk",
      customer_name: "Peter Kováč",
      shipping_country: "SK",
      created_at: "2026-05-11T07:00:00Z",
    },
  },
  {
    id: "6",
    platform_source: "zbozi",
    external_review_id: "zb-006",
    country_code: "CZ",
    rating: 1,
    review_text: "Objednávka přišla poškozená, kontaktoval jsem podporu a stále čekám na odpověď.",
    review_text_cz: "Objednávka přišla poškozená, kontaktoval jsem podporu a stále čekám na odpověď.",
    customer_name_extracted: "Tomáš Dvořák",
    order_id: null,
    match_confidence: "unverified",
    ai_category: "logistics",
    ai_sentiment: "negative",
    response_draft: null,
    status: "pending",
    created_at: "2026-05-13T15:30:00Z",
    replied_at: null,
  },
  {
    id: "7",
    platform_source: "trusted_shops",
    external_review_id: "ts-007",
    country_code: "AT",
    rating: 4,
    review_text: "Schöne Produkte, faire Preise. Versand nach Österreich ging schnell.",
    review_text_cz: "Hezké produkty, férové ceny. Doprava do Rakouska byla rychlá.",
    customer_name_extracted: "Eva Steiner",
    order_id: "ord-105",
    match_confidence: "fuzzy",
    ai_category: "mixed",
    ai_sentiment: "positive",
    response_draft: "Herzlichen Dank für Ihre Bewertung, Eva! Wir freuen uns über Ihr positives Feedback.",
    status: "pending",
    created_at: "2026-05-12T08:00:00Z",
    replied_at: null,
    order: {
      id: "ord-105",
      external_order_id: "WV-AT-20260509-008",
      customer_email: "eva.steiner@a1.at",
      customer_name: "Eva Steiner",
      shipping_country: "AT",
      created_at: "2026-05-09T14:00:00Z",
    },
  },
  {
    id: "8",
    platform_source: "firmy",
    external_review_id: "fi-008",
    country_code: "CZ",
    rating: 5,
    review_text: "Nejlepší e-shop s vlnou v ČR! Vždy spolehliví.",
    review_text_cz: "Nejlepší e-shop s vlnou v ČR! Vždy spolehliví.",
    customer_name_extracted: null,
    order_id: null,
    match_confidence: "unverified",
    ai_category: "service",
    ai_sentiment: "positive",
    response_draft: "Děkujeme za krásnou recenzi! Jsme rádi, že jste s námi spokojeni.",
    status: "pending",
    created_at: "2026-05-14T07:00:00Z",
    replied_at: null,
  },
  {
    id: "9",
    platform_source: "trusted_shops",
    external_review_id: "ts-009",
    country_code: "FR",
    rating: 3,
    review_text: "La laine est de bonne qualité mais le site n'est pas disponible en français.",
    review_text_cz: "Vlna je kvalitní, ale stránky nejsou dostupné ve francouzštině.",
    customer_name_extracted: "Marie Dupont",
    order_id: null,
    match_confidence: "unverified",
    ai_category: "web",
    ai_sentiment: "neutral",
    response_draft: null,
    status: "pending",
    created_at: "2026-05-11T18:00:00Z",
    replied_at: null,
  },
  {
    id: "10",
    platform_source: "trusted_shops",
    external_review_id: "ts-010",
    country_code: "IT",
    rating: 4,
    review_text: "Ottima lana merino, spedizione veloce. Consigliato!",
    review_text_cz: "Výborná merino vlna, rychlé doručení. Doporučuji!",
    customer_name_extracted: "Giulia Rossi",
    order_id: "ord-106",
    match_confidence: "exact",
    ai_category: "product",
    ai_sentiment: "positive",
    response_draft: "Grazie mille per la sua recensione, Giulia! Siamo felici che sia soddisfatta dei nostri prodotti.",
    status: "ignored",
    created_at: "2026-05-08T12:00:00Z",
    replied_at: null,
    order: {
      id: "ord-106",
      external_order_id: "WV-IT-20260506-002",
      customer_email: "giulia.rossi@libero.it",
      customer_name: "Giulia Rossi",
      shipping_country: "IT",
      created_at: "2026-05-06T09:00:00Z",
    },
  },
];
